.PHONY: clean All

All:
	@echo "----------Building project:[ Car_wash - Debug ]----------"
	@cd "Repeater" && "$(MAKE)" -f  "Car_wash.mk"
clean:
	@echo "----------Cleaning project:[ Car_wash - Debug ]----------"
	@cd "Repeater" && "$(MAKE)" -f  "Car_wash.mk" clean
